name: workflow
run-name: ${{ github.actor }} is running
on: [push]
jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: linux
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1